version: 2.1

orbs: 
    node: circleci/node@3.0.0

jobs:
    build:
        docker:
            - image: circleci/node:{{circleci/node@3.0.0}} # Use the node orb with the specified version
        steps: 
            - checkout
            - node/install-packages
            - run:
                name: Run tests
                command: npm test

workflows:
    sample:
        jobs:
            - build
