version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.13.0
    steps: 
      - checkout
      - node/install-packages
      - run:
          name: Build Project   
          command: npm run build
      # - run:
      #     name: Run tests
      #     command: npm test

  deploy:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Deploy Project
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  sample:
    jobs:
      - build
      # Trigger the deploy job only when the build job is successful
      - deploy:
          requires:
            - build
