version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: cimg/node:15.1
    steps: 
      - checkout
      - node/install-packages
      - run:
          name: Build Project   
          command: npm run build
      # - run:
      #     name: Run tests
      #     command: npm test

  deploy:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install Firebase CLI Locally
          command: npm install firebase-tools --save-dev
      - run:
          name: Firebase Login
          command: npx firebase login:ci --no-localhost --token $FIREBASE_TOKEN
      - run:
          name: Deploy to Firebase Hosting
          command: npx firebase deploy --only hosting

workflows:
  sample:
    jobs:
      - build
      # Trigger the deploy job only when the build job is successful
      - deploy:
          requires:
            - build
