version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.13.0
    steps: 
      - checkout
      - node/install-packages
      - run:
          name: Build Project   
          command: npm run build
      # - run:
      #     name: Run tests
      #     command: npm test

  deploy:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install Firebase CLI
          command: npm install firebase-tools
      - run:
          name: Authenticate Firebase CLI
          command: |
            echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > $HOME/firebase-service-account.json
            ./node_modules/.bin/firebase use --add --token="$FIREBASE_SERVICE_ACCOUNT_KEY"
      - run:
          name: Deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --only hosting

workflows:
  sample:
    jobs:
      - build
      # Trigger the deploy job only when the build job is successful
      - deploy:
          requires:
            - build
